<?php $this->layout('template', compact('active')) ?>

<?php $this->start('intro') ?>

<div class="container">
    <p class="text-center"><img src="/img/cccf-logo.png" alt="Cook County Community Fund Logo"></p>
</div>

<?php $this->stop() ?>

<div class="container">
    <h1>Our Mission</h1>
    <p class="lead">The Mission of the Cook County Community Fund is to enhance the quality of life for the people of Cook County by attracting charitable gifts, making philanthropic grants, and providing responsible financial stewardship and community leadership.</p>
    <hr>

    <div class="row">
        <div class="col-md-8">
            <p>The Cook County Community Fund was established in 2003 by area residents to build a permanent endowed fund to meet the charitable needs of the Cook County area.  An affiliate fund of the <a href="http://www.dsacommunityfoundation.com/" target="_blank">Duluth Superior Area Community Foundation</a>, the Cook County Community Fund taps into management expertise, administrative support, and the advantage of pooling resources for investment provided by the Duluth Superior Area Community Foundation to enhance the quality of life in the Cook County area.</p>
            <p>Each year, the Cook County Community Fund <a href="/board">Advisory Board</a> meets to recommend funding that meets community needs in the following areas: Arts, Community Development, Education, Environment, Human Services and Youth. Grants from the fund range from $500-$2,500. The deadline to apply is March 1st.</p>
        </div>
        <div class="col-md-4">
            <p class="text-muted">Have something to send to us?</p>
            <address>
                <strong>Cook County Community Fund</strong><br/>
                P.O. Box 763<br>
                Grand Marais, MN 55604
            </address>

            <p class="text-muted">Need to get in touch?</p>
            <p>You can email <a href="mailto:woody.gilk@gmail.com">Woody</a> or <a href="mailto:rvos@mathisonlawoffice.com ">Ruthanne</a>.</p>
        </div>
</div>
