<?php $this->layout('template', compact('active')) ?>

<?php $this->start('intro') ?>

<div class="container">
    <h1>Our Board</h1>
    <p>The volunteer board of the CCCF are all residents of Cook County. <strong>We are looking for more board members.</strong> If you are interested in joining the board, please contact a board member.</p>
</div>

<?php $this->stop() ?>
<div class="container board">
    <div class="row">
        <div class="col-md-4"><img src="/img/board/ruthanne-vos.jpg" alt="Ruthanne Vos"></div>
        <div class="col-md-8">
            <h2>Ruthanne Hedstrom Vos <small>co-chair</small></h2>
            <p>Ruthanne is a native of Grand Marais, and after many years away, now divides her time between Grand Marais and the Twin Cities metro area, working as an estate planning attorney with Mathison Law Office in Grand Marais.<p>
            <p>Ruthanne is passionate about Cook County and is honored to serve on the Cook County Community Fund advisory board where she focuses on raising community awareness of the Community Fund and the role it serves in ensuring local non-profits remain strong and viable.</p>
            <p>When not on the road between Grand Marais and the Twin Cities, Ruthanne enjoys spending time at her cabin on Devil Track Lake with her family – husband Jim, adult daughters Stephanie and Allison, and her golden retriever, Kobi, who accompanies her to the office some days.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4"><img src="/img/board/woody-gilk.jpg" alt="Woody Gilk"></div>
        <div class="col-md-8">
            <h2>Woody Gilk <small>co-chair</small></h2>
            <p>Woody has been a part time member of the community his whole life, moving here permanently in 2009 after spending several years working around the midwest and internationally. He is a computer programmer working remotely for a St. Paul company and providing technical assistance to local non-profits.</p>
            <p>As a member of the Cook County Community Fund he focuses on community education, digital outreach, and strategy. In addition, he sits on the board of the Cook County Broadband Commission and consults with the Cook County Local Energy project as a technical advisor.</p>
            <p>When not sitting in front of a computer, he likes to bike, run, cook, and spend time with his daughter. Woody and his wife Gwen currently live in Coville, near Grand Marais.</p>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-4"><img src="/img/board/nancy-hemstad-seaton.jpg" alt="Nancy Hemstad Seaton"></div>
        <div class="col-md-8">
            <h2>Nancy Hemstad Seaton <small>secretary</small></h2>
            <p>Nancy and her husband David own and operate Hungry Jack Outfitters and will mark their 25th year on the edge of the Boundary Waters in 2016. Their nest is now empty; their young adult sons having flown off into the world.</p>
            <p>Nancy has been lucky enough to call the Gunflint Trail home since the 80’s; having spent college summers working at Gunflint Northwoods Outfitters, painting watercolors and observing her neighborhood.</p>
            <p>Her winters are busy with art interests.  Primarily known as a watercolor artist, she is flowing into the colorful world of fused glass. She creates and teaches at the Grand Marais Art Colony and her work can be seen at Siverston Gallery in Grand Marais.</p>
            <p>With many varied interests she has been active on the boards of the Grand Marais Art Colony, Gunflint Trail Association and the First Congregational UCC of Grand Marais. After the Ham Lake Fire in 2007 she coordinated Gunflint Green Up, an event that planted 75,000 trees with nearly 500 volunteers. She is currently the chair of the Gunflint Trail Scenic Byway Committee.</p> 
        </div>
    </div>
    <div class="row">
        <div class="col-md-4"><img src="/img/board/karen-halbersleben.jpg" alt="Karen Halbersleben"></div>
        <div class="col-md-8">
            <h2>Karen Halbersleben <small>deputy secretary</small></h2>
            <p>Karen Halbersleben is a child of the Great Lakes, growing up on Lake Erie in Buffalo and living and working on Lake Ontario in Oswego, NY, before finally discovering the Greatest of them all: Lake Superior.</p>
            <p>Karen is a British Historian, with specialties in women's history and the history of social reform movements.  She was a Professor of History in the State University of New York system, at Oswego, where she met and married her husband Jack Miller.  After moving into academic administration, Karen held leadership posts at the University of Richmond, Buena Vista University, and Northland College.  She and Jack have been full-time Grand Marais residents since 2009, and volunteer with Meals on Wheels and Ruby's Pantry.</p>
            <p>Karen also holds local leadership roles with Cook County Higher Education and Spirit of the Wilderness Episcopal Church.  She teaches a variety of courses and gives lectures in British History through the Higher Ed center.</p> 
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-4"><img src="/img/board/kaitlyn-bohlin.jpg" alt="Kaitlyn Bohlin"></div>
        <div class="col-md-8">
            <h2>Kaitlyn Bohlin</h2>
            <p>Kaitlyn first fell in love with Lake Superior as a young woman on a summer camp backpacking trip; since then, she has wandered far and wide from the deserts of Utah to the peaks of the Andes but nothing feels like home quite as much as the northern woods. Originally hailing from Chicago, she packed her bags and moved to Grand Marais in June of 2013, taking a job as Development Manager at North House Folk School.</p>
            <p>Kaitlyn is pleased to bring her background in community outreach, resource advancement, and nonprofit administration to the Cook County Community Fund. She also serves on the board at First Congregational UCC and provides contract work to local nonprofits in marketing and development.</p>
            <p>Kaitlyn's professional passions lie in arts and education, and when she's not at her desk planning outreach campaigns, she can be found hiking, knitting, tinkering on the banjo, or playing in the yard with her cat Sushi.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4"><img src="/img/board/bruce-kerfoot.jpg" alt="Bruce Kerfoot"></div>
        <div class="col-md-8">
            <h2>Bruce Kerfoot</h2>
            <p>Bruce has over 50 years of experience as a small business owner and is very active in various non-profit organizations, from the American Red Cross to the Boy Scouts to the Fire Department.</p>
            <p>He currently serves on a number of non-profit boards within Cook County.</p> 
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">&nbsp;</div>
        <div class="col-md-8">
            <h2>Mary Petz</h2>
            <p><em>Bio coming soon.</em></p> 
        </div>
    </div>
    <div class="row">
        <div class="col-md-4"><img src="/img/board/amber-pratt.jpg" alt="Amber Pratt"></div>
        <div class="col-md-8">
            <h2>Amber Pratt</h2>
            <p><em>Bio coming soon.</em></p> 
        </div>
    </div>
    <div class="row">
        <div class="col-md-4"><img src="/img/board/kelsey-rogers-kennedy.jpg" alt="Kelsey Rogers Kennedy"></div>
        <div class="col-md-8">
            <h2>Kelsey Rogers Kennedy</h2>
            <p>Kelsey is a Cook County High School Graduate, and has B.A. Social Marketing, Northern Michigan University; M.S. Organizational Leadership, St. Mary’s University. Kelsey moved back to Grand Marais in 2011. Kelsey is the Program Coordinator at Cook County Higher Education and is in a slow transition of taking over Birchbark Books and Gifts.</p>
            <p>Kelsey loves the community that she was raised in and feels it is vital to find ways to give back.  Kelsey is happy to be part of the Cook County Community Fund. She also gives her time by serving on the Boreal Community Media Board, Cook County Community Education Board, and as the coordinator for Empty Bowls.</p>
            <p>When Kelsey finds down time, she enjoys traveling, playing with her dog Rita, dining out or cooking in, reading, picking berries, and spending time with her husband, family, and friends.</p>
        </div>
    </div>
</div>
<div class="container alumni">
    <hr>
    <div class="row">
        <div class="col-md-4">
            <h3 class="text-center">Alumni</h3>
        </div>
        <div class="col-md-8">
            <p>Cook County Community Fund would also like to recognize the following past board members for their service to the community: Tracy Benson, Mike Carlson, Howard Hedstrom, Richard Olson, Ann Possis, and Sue Riley.</p>
        </div>
    </div>
</div>
