<?php $this->layout('template', compact('active')) ?>

<?php $this->start('intro') ?>

<div class="container">
    <h1>Non-profit Directory</h1>
    <p>The following directory of non-profits is made possible by a partnership with the <a href="http://cookcountychamber.org/">Cook County Chamber of Commerace</a>.</p>
</div>

<?php $this->stop() ?>

<div class="container">
    <table id="directory" class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Address</th>
                <th>Phone Number</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($directory as $row): ?>
            <tr>
                <td><?= $this->directory()->name($row) ?></td>
                <td><?= $this->directory()->address($row) ?></td>
                <td><?= $this->directory()->phone($row) ?></td>
                <td><?= $this->directory()->email($row) ?></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
