<?php $this->layout('template', compact('active')) ?>

<?php $this->start('intro') ?>

<div class="container">
    <h1>Non-profit Directory</h1>
    <p>The following directory of non-profits is made possible by a partnership with the <a href="http://cookcountychamber.org/">Cook County Chamber of Commerace</a>.</p>
</div>

<?php $this->stop() ?>

<div class="container">
    <p><em>Directory coming soon.</em></p>
</div>
