<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <title>Cook County Community Fund</title>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href="//cdn.datatables.net/s/bs/dt-1.10.10/datatables.min.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
    <script src="/js/ie10-viewport-bug-workaround.js"></script>
</head>

<body>

    <nav class="navbar navbar-inverse navbar-static-top">
        <div class="container">
            <a class="navbar-brand" href="/">Cook County Community Fund</a>
            <ul class="nav navbar-nav navbar-right">
                <?php foreach ($pages as $link => $page): ?>
                <?php $is_active = strtolower($page) === $active; ?>
                <li class="nav-item <?= $is_active ? 'active' : '' ?>">
                    <a class="nav-link" href="<?= $link ?>"><?= $page ?>
                        <?php if ($is_active): ?>
                            <span class="sr-only">(current)</span>
                        <?php endif ?>
                    </a>
                </li>
                <?php endforeach ?>
            </ul>
        </div>
    </nav>

    <?php if ($this->section('intro')): ?>
    <div class="jumbotron">
        <?= $this->section('intro') ?>
    </div>
    <?php endif ?>

    <?= $this->section('content') ?>

    <div class="container">
        <hr>
        <footer>
            <p class="text-center">Copyright &copy; 2016 Cook County Community Fund</p>
        </footer>
    </div>


    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="/js/jquery.min.js"><\/script>')</script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="//cdn.datatables.net/s/bs/dt-1.10.10/datatables.min.js"></script>
    <script src="/js/app.js"></script>
</body>
</html>
